travis:
  secure:
    BINSTAR_TOKEN: I0LqokZvxaqN+J1OdAzB22ZnZxsFFautyj28A1h/6OXQRbtuDm5q3Xb2ZHKJRuFrNOrexBz1fuYWfuelBh455PVuTsmFD6etvr14iDPpgXCY3T+RV/YCMpifXTFc5wkT72O3frtZhs4YPqFrP4fYqt2x65XZ1dHZRavQHYul/H45XrHJoA3za9vqkrYvB+a2g4jNRR/R9B+5jEwLevcisdXGiLWJ0WFAA0VAdCWDQ5bo+ntss6lfFC9ndK/dA9KTtsGDsC6N/zjOu5ItNyNil7aDfSxKkQsrW5lNDHEhWvY8Es2io9j9AkDySjRKx5RxBCQ9M6uqDa9SvSO1Cl3e8a0nvyeSg0LAhg8aTwULyl4vboT/6ncm957GilrrnLdRIYZrmsMD9RNYIFCyDBds9vrtJe4Xva/5RFbNPaIUrn5dKPnMwdi+euuNJwQNaeNpC8h+WZrQugg4j7yLm8pMHjlWbYAovv1ze2R26AvmpYbjPbE0EUVNV93bDC7cunvRojn4FV9D8a/Tn0jBqjmfxwpsOfLCZUXvDeGvd5yqkfGhdjoyvT0BiYDdR5VbtYqZE5tbKj9QhetMP1kOWhxmNzn07GAE6Ym/V0qIYDHwHquVQtF/ptYSh81erH3rDUJd8M263Qu0F2ccgYEcUGhkN8Izx/43STDAYmNTSNP6rcM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
